name: Code Quality Checks

on:
  push:
    branches: ["**"]
    tags: ["*"]

jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Test environment
        run: pip install -e ."[test]"

      - name: Test with isort
        run: isort --check-only --diff .

      - name: Test with refurb
        run: refurb . --quiet
  windows-latest:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Test environment
        run: pip install -e ."[test]"

  macos-latest:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Test environment
        run: pip install -e ."[test]"
