name: Code Quality Checks

on:
  push:
    branches: ["**"]
    tags: ["*"]

jobs:
  code-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Test with isort
        run: |
          pip install isort
          isort --check-only --diff .

      - name: Test with refurb
        run: |
          pip install refurb
          refurb . --quiet

  different-OS:
    runs-on: ${{ matrix.os }}
    needs: [code-checks]

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Test environment
        run: pip install -e .

      - name: Test with pytest
        run: |
          pip install pytest
          pytest

  different-OS-with-swig:
    runs-on: ${{ matrix.os }}
    needs: [code-checks]

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Test environment
        run: pip install -e ".[with_swig]"

      - name: Test with pytest
        run: |
          pip install pytest
          pytest
