name: docs

on: push

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install requirements
      run: |
        pip3 install sphinx-rtd-theme
        pip install -e ".[with_swig]"
    
    - name: Build docs
      run: |
        cd docs
        make html
    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html/