name: docs

on: 
  push:
    branches: ["main"]

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install PlantUML
      run: |
        sudo apt-get update
        sudo apt-get install -y plantuml

    - name: Set PLANTUML_JAR environment variable
      run: echo "PLANTUML_JAR=$(find /usr/share/plantuml/ -name 'plantuml.jar')" >> $GITHUB_ENV

    - name: Install requirements
      run: |
        pip3 install sphinx-rtd-theme
        pip3 install sphinxcontrib-plantuml
        pip3 install sphinx_copybutton
        pip3 install graphviz
        pip install -e ".[with_swig]"
    
    - name: Build docs
      run: |
        cd docs
        make clean html
    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html/